<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netcoreapp3.1;net5.0;net6.0;net8.0;net10.0</TargetFrameworks>
    <Version>0.3.0</Version>
    <Authors>hfrances</Authors>
    <Company>TrCode</Company>
    <Product>qckdev.AspNetCore.Authentication.JwtBearer (Preview)</Product>
    <Description>Provides tools to configure JWT bearer authentication.</Description>
    <PackageProjectUrl>https://github.com/hfrances/qckdev.AspNetCore.Authentication.JwtBearer</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.1'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.32" />
    <!-- Mitigate vulnerability GHSA-59j7-ghrg-fj52 by explicitly upgrading IdentityModel packages -->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.34.0" />
    <!-- Mitigate vulnerability GHSA-5crp-9r3c-p9vr by explicitly upgrading Newtonsoft.Json -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net5.0'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.17" />
    <!-- Mitigate vulnerability GHSA-59j7-ghrg-fj52 by explicitly upgrading IdentityModel packages -->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.34.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net6.0'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.26" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net10.0'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>